<% project = 'tboard' %>
<% repo = Grit::Repo.new(Rails.root).head.name rescue nil %>
<% dbname = lambda{|env| [project, env, repo].compact.join('_') } %>
defaults: &defaults
  adapter: sqlite3
  pool: 5
  timeout: 5000

development: &development
  <<: *defaults
  database: db/<%= dbname[:development] %>.sqlite3

test:
  <<: *defaults
  database: db/<%= dbname[:test] %>.sqlite3

production: &production
  <<: *defaults
  database: tboard_production
  username: username
  password: password

